//
//  PDFDocumentGenerator.swift
//  LegalDocGenerator
//
//  Generates PDF documents from legal document data
//

import Foundation
import UIKit
import PDFKit

class PDFDocumentGenerator {
    static let shared = PDFDocumentGenerator()

    private init() {}

    func generateDocument(_ document: LegalDocument) -> URL? {
        let pdfData = createPDF(from: document)

        let tempDir = FileManager.default.temporaryDirectory
        let pdfURL = tempDir.appendingPathComponent("\(document.documentId).pdf")

        do {
            try pdfData.write(to: pdfURL)
            return pdfURL
        } catch {
            print("Error saving PDF: \(error)")
            return nil
        }
    }

    private func createPDF(from document: LegalDocument) -> Data {
        let pdfMetaData = [
            kCGPDFContextCreator: "Helion Prime Legal Document Generator",
            kCGPDFContextAuthor: "Helion Prime Financial Trust",
            kCGPDFContextTitle: document.title
        ]

        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]

        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter size
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)

        let data = renderer.pdfData { context in
            context.beginPage()

            let titleFont = UIFont.boldSystemFont(ofSize: 20)
            let bodyFont = UIFont.systemFont(ofSize: 12)
            let smallFont = UIFont.systemFont(ofSize: 10)

            var yPosition: CGFloat = 50

            // Title
            let titleAttributes: [NSAttributedString.Key: Any] = [
                .font: titleFont,
                .foregroundColor: UIColor.black
            ]
            let titleString = document.documentType.rawValue
            let titleSize = titleString.size(withAttributes: titleAttributes)
            let titleX = (pageRect.width - titleSize.width) / 2
            titleString.draw(at: CGPoint(x: titleX, y: yPosition), withAttributes: titleAttributes)
            yPosition += titleSize.height + 20

            // Document ID and Date
            let smallAttributes: [NSAttributedString.Key: Any] = [
                .font: smallFont,
                .foregroundColor: UIColor.gray
            ]
            let idString = "Document ID: \(document.documentId)"
            idString.draw(at: CGPoint(x: 50, y: yPosition), withAttributes: smallAttributes)
            yPosition += 15

            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .long
            let dateString = "Date: \(dateFormatter.string(from: document.createdDate))"
            dateString.draw(at: CGPoint(x: 50, y: yPosition), withAttributes: smallAttributes)
            yPosition += 30

            // Document content
            let bodyAttributes: [NSAttributedString.Key: Any] = [
                .font: bodyFont,
                .foregroundColor: UIColor.black
            ]

            let contentWidth: CGFloat = pageRect.width - 100
            let template = getTemplate(for: document.documentType)
            let content = template.generateContent(data: document.data, documentId: document.documentId)

            for section in content {
                let font = section.isHeading ? UIFont.boldSystemFont(ofSize: 14) : bodyFont
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: UIColor.black
                ]

                let text = section.text
                let textSize = text.boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attrs,
                    context: nil
                )

                // Start new page if needed
                if yPosition + textSize.height > pageRect.height - 50 {
                    context.beginPage()
                    yPosition = 50
                }

                text.draw(
                    in: CGRect(x: 50, y: yPosition, width: contentWidth, height: textSize.height),
                    withAttributes: attrs
                )
                yPosition += textSize.height + 10
            }

            // Footer
            let footerY = pageRect.height - 40
            let footerText = "Generated by Helion Prime Legal Document Generator"
            footerText.draw(at: CGPoint(x: 50, y: footerY), withAttributes: smallAttributes)
        }

        return data
    }

    private func getTemplate(for documentType: DocumentType) -> DocumentTemplate {
        switch documentType {
        case .mortgageSatisfaction: return MortgageSatisfactionTemplate()
        case .powerOfAttorney: return PowerOfAttorneyTemplate()
        case .nda: return NDATemplate()
        case .employmentContract: return EmploymentContractTemplate()
        case .lease: return LeaseAgreementTemplate()
        case .promissoryNote: return PromissoryNoteTemplate()
        case .billOfSale: return BillOfSaleTemplate()
        case .lastWillTestament: return LastWillTestamentTemplate()
        case .businessContract: return BusinessContractTemplate()
        case .serviceAgreement: return ServiceAgreementTemplate()
        }
    }
}
