//
//  TextDocumentGenerator.swift
//  LegalDocGenerator
//
//  Generates plain text documents
//

import Foundation

class TextDocumentGenerator {
    static let shared = TextDocumentGenerator()

    private init() {}

    func generateDocument(_ document: LegalDocument) -> URL? {
        let textContent = createText(from: document)

        let tempDir = FileManager.default.temporaryDirectory
        let textURL = tempDir.appendingPathComponent("\(document.documentId).txt")

        do {
            try textContent.write(to: textURL, atomically: true, encoding: .utf8)
            return textURL
        } catch {
            print("Error saving text document: \(error)")
            return nil
        }
    }

    private func createText(from document: LegalDocument) -> String {
        var output = ""

        // Header
        output += "=" * 70 + "\n"
        output += document.documentType.rawValue.center(70) + "\n"
        output += "=" * 70 + "\n\n"

        output += "Document ID: \(document.documentId)\n"

        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .long
        output += "Date: \(dateFormatter.string(from: document.createdDate))\n"
        output += "\n"

        // Content
        let template = getTemplate(for: document.documentType)
        let content = template.generateContent(data: document.data, documentId: document.documentId)

        for section in content {
            if section.isHeading {
                output += "\n" + section.text + "\n"
                output += String(repeating: "-", count: section.text.count) + "\n"
            } else {
                output += section.text + "\n"
            }
        }

        // Footer
        output += "\n" + "=" * 70 + "\n"
        output += "Generated by Helion Prime Legal Document Generator\n"
        output += "© 2026 Helion Prime Financial Trust\n"

        return output
    }

    private func getTemplate(for documentType: DocumentType) -> DocumentTemplate {
        switch documentType {
        case .mortgageSatisfaction: return MortgageSatisfactionTemplate()
        case .powerOfAttorney: return PowerOfAttorneyTemplate()
        case .nda: return NDATemplate()
        case .employmentContract: return EmploymentContractTemplate()
        case .lease: return LeaseAgreementTemplate()
        case .promissoryNote: return PromissoryNoteTemplate()
        case .billOfSale: return BillOfSaleTemplate()
        case .lastWillTestament: return LastWillTestamentTemplate()
        case .businessContract: return BusinessContractTemplate()
        case .serviceAgreement: return ServiceAgreementTemplate()
        }
    }
}

extension String {
    static func *(lhs: String, rhs: Int) -> String {
        return String(repeating: lhs, count: rhs)
    }

    func center(_ width: Int) -> String {
        let length = self.count
        if length >= width { return self }
        let padding = (width - length) / 2
        let leftPad = String(repeating: " ", count: padding)
        let rightPad = String(repeating: " ", count: width - length - padding)
        return leftPad + self + rightPad
    }
}
