//
//  WordDocumentGenerator.swift
//  LegalDocGenerator
//
//  Generates Microsoft Word (.docx) documents
//

import Foundation
import UniformTypeIdentifiers

class WordDocumentGenerator {
    static let shared = WordDocumentGenerator()

    private init() {}

    func generateDocument(_ document: LegalDocument) -> URL? {
        let template = getTemplate(for: document.documentType)
        let populatedContent = populateTemplate(template, with: document)

        let wordXML = createWordXML(content: populatedContent, document: document)

        return saveAsDocx(wordXML, documentId: document.documentId)
    }

    // MARK: - Word XML Generation

    private func createWordXML(content: String, document: LegalDocument) -> String {
        return """
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
                    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
            <w:body>
                \(content)
                <w:sectPr>
                    <w:pgSz w:w="12240" w:h="15840"/>
                    <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/>
                </w:sectPr>
            </w:body>
        </w:document>
        """
    }

    private func createParagraph(_ text: String, style: ParagraphStyle = .normal) -> String {
        let fontSize = style.fontSize
        let isBold = style.isBold
        let isItalic = style.isItalic
        let alignment = style.alignment

        return """
        <w:p>
            <w:pPr>
                <w:jc w:val="\(alignment)"/>
                <w:spacing w:before="120" w:after="120"/>
            </w:pPr>
            <w:r>
                <w:rPr>
                    <w:sz w:val="\(fontSize)"/>
                    <w:szCs w:val="\(fontSize)"/>
                    \(isBold ? "<w:b/>" : "")
                    \(isItalic ? "<w:i/>" : "")
                    <w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>
                </w:rPr>
                <w:t xml:space="preserve">\(text.xmlEscaped())</w:t>
            </w:r>
        </w:p>
        """
    }

    private func createHeading(_ text: String, level: Int = 1) -> String {
        let fontSize = 32 - (level * 4) // Heading sizes
        return createParagraph(text, style: ParagraphStyle(
            fontSize: fontSize,
            isBold: true,
            alignment: "center"
        ))
    }

    // MARK: - Template System

    private func getTemplate(for documentType: DocumentType) -> DocumentTemplate {
        switch documentType {
        case .mortgageSatisfaction:
            return MortgageSatisfactionTemplate()
        case .powerOfAttorney:
            return PowerOfAttorneyTemplate()
        case .nda:
            return NDATemplate()
        case .employmentContract:
            return EmploymentContractTemplate()
        case .lease:
            return LeaseAgreementTemplate()
        case .promissoryNote:
            return PromissoryNoteTemplate()
        case .billOfSale:
            return BillOfSaleTemplate()
        case .lastWillTestament:
            return LastWillTestamentTemplate()
        case .businessContract:
            return BusinessContractTemplate()
        case .serviceAgreement:
            return ServiceAgreementTemplate()
        }
    }

    private func populateTemplate(_ template: DocumentTemplate, with document: LegalDocument) -> String {
        var content = template.generateContent(data: document.data, documentId: document.documentId)

        // Create Word XML paragraphs
        var wordContent = ""

        // Title
        wordContent += createHeading(document.documentType.rawValue, level: 1)

        // Document ID and Date
        let formatter = DateFormatter()
        formatter.dateStyle = .long
        let dateString = formatter.string(from: document.createdDate)

        wordContent += createParagraph("Document ID: \(document.documentId)", style: .small)
        wordContent += createParagraph("Date: \(dateString)", style: .small)
        wordContent += createParagraph("") // Empty line

        // Content sections
        for section in content {
            if section.isHeading {
                wordContent += createHeading(section.text, level: 2)
            } else {
                wordContent += createParagraph(section.text, style: section.style)
            }
        }

        // Footer
        wordContent += createParagraph("") // Empty line
        wordContent += createParagraph(String(repeating: "_", count: 50), style: .small)
        wordContent += createParagraph("Generated by Helion Prime Legal Document Generator", style: .small)
        wordContent += createParagraph("© 2026 Helion Prime Financial Trust", style: .small)

        return wordContent
    }

    // MARK: - File Saving

    private func saveAsDocx(_ wordXML: String, documentId: String) -> URL? {
        let fileManager = FileManager.default
        let tempDir = fileManager.temporaryDirectory
        let docxURL = tempDir.appendingPathComponent("\(documentId).docx")

        // Create the minimal .docx structure (simplified version)
        // A full .docx is a ZIP file with multiple XML files
        // For simplicity, we'll create a single document.xml wrapped in basic structure

        let fullDocument = createMinimalDocx(wordXML: wordXML)

        do {
            try fullDocument.write(to: docxURL, atomically: true, encoding: .utf8)
            return docxURL
        } catch {
            print("Error saving Word document: \(error)")
            return nil
        }
    }

    private func createMinimalDocx(wordXML: String) -> String {
        // This creates a simplified Word XML document
        // In production, you'd use a proper ZIP library to create the full .docx structure
        return wordXML
    }

    // MARK: - Helper Structures

    struct ParagraphStyle {
        var fontSize: Int = 24 // 12pt = 24 half-points
        var isBold: Bool = false
        var isItalic: Bool = false
        var alignment: String = "left" // left, center, right, both (justified)

        static let normal = ParagraphStyle()
        static let bold = ParagraphStyle(isBold: true)
        static let small = ParagraphStyle(fontSize: 18, isItalic: true)
        static let centered = ParagraphStyle(alignment: "center")
    }

    struct ContentSection {
        let text: String
        let isHeading: Bool
        let style: ParagraphStyle

        init(text: String, isHeading: Bool = false, style: ParagraphStyle = .normal) {
            self.text = text
            self.isHeading = isHeading
            self.style = style
        }
    }
}

// MARK: - Extensions

extension String {
    func xmlEscaped() -> String {
        return self
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }
}

// MARK: - Document Template Protocol

protocol DocumentTemplate {
    func generateContent(data: [String: String], documentId: String) -> [WordDocumentGenerator.ContentSection]
}
